### PR TITLE
Modified BleemSync to not rely on "1/GameData" structure anymore. Gam…

### PR DESCRIPTION
**Pull request by bbsan2k**
Folders are now symlinked with auto generated IDs at BootTime

### CODE REVIEW

**Comment by pathartl** [comment]
Did you test this on-system? I currently have a branch open for this but it wasn't very stable.

**Comment by radium-v** [comment]
Would this break things for those who are already using the `{n}/GameData` folder structure?

**Comment by swingflip** [comment]
This PR is needs reviewing and redoing as it doesn't fit with the current structure of the new payload

**Comment by swingflip** [comment]
Closed PR too as it needs to pushed to the Develop branch

**Comment by bbsan2k** [comment]
The BleemSync C# changes can still be used. The boot.sh needs to be re-done.

**Pull request closed without merging**
