### PR TITLE
Feature/rebuild database utility

### PR DESCRIPTION
**Pull request by pathartl**
Added a feature to allow users to rebuild the database. This could potentially fix peoples systems where covers are blank or a game is missing.

### CODE REVIEW

**Comment by GMMan** [comment]
`GameManagerService` is not resolving in `SettingsController` because you are requesting a concrete class instead of an interface.

image

**Comment by GMMan** [comment]
image

I think the existing files are being moved to themselves.

**Comment by swingflip** [comment]
🍿

**Comment by GMMan** [comment]
It builds and completes now, but only rebuilds the `GAME` table, and not the `DISC` table.

**Comment by pathartl** [comment]
Sorry, try one last time. It's no longer using AddGame() to the database rebuild. It's not the greatest solution, but should be fine for getting the hotfix out the door. The service is changing a bit in the desktop UI implementation, so we can clean it up then instead of introducing a bunch of edge-case scenarios into a hotfix.

**Pull request merged**
